# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-12 04:31
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CtrlBase',
            fields=[
                ('ctrl_id', models.AutoField(primary_key=True, serialize=False)),
                ('ctrl_name', models.CharField(max_length=45)),
                ('ctrl_description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Controller',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CtrlBom',
            fields=[
                ('ctrl_bom_id', models.AutoField(primary_key=True, serialize=False)),
                ('elements_quantity', models.IntegerField()),
                ('ctrl', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kurs.CtrlBase')),
            ],
            options={
                'verbose_name': 'BOM',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ElementsBase',
            fields=[
                ('element_id', models.AutoField(primary_key=True, serialize=False)),
                ('element_articul', models.CharField(max_length=30)),
                ('element_name', models.CharField(max_length=45)),
                ('element_description', models.CharField(blank=True, max_length=200, null=True)),
                ('elements_footprint', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Element',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=45, unique=True)),
                ('invoice_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Invoice',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=45)),
                ('order_date', models.DateTimeField()),
                ('ctrl_quantity', models.IntegerField()),
                ('ctrl', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kurs.CtrlBase')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PurchasesConsumption',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('elements_quantity', models.IntegerField()),
                ('element_price', models.FloatField()),
                ('p_c', models.BooleanField()),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kurs.ElementsBase')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kurs.Invoices')),
            ],
            options={
                'verbose_name': 'Purchase/Consumption',
                'managed': True,
                'verbose_name_plural': 'Purchases/Consumptions',
            },
        ),
        migrations.CreateModel(
            name='SuppliersCustomersBase',
            fields=[
                ('supplier_customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_customer_identify', models.BooleanField()),
                ('supplier_customer_name', models.CharField(max_length=100)),
                ('supplier_customer_info', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'managed': True,
                'verbose_name_plural': 'Suppliers/Customers',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kurs.SuppliersCustomersBase'),
        ),
        migrations.AddField(
            model_name='invoices',
            name='supplier_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kurs.SuppliersCustomersBase'),
        ),
        migrations.AddField(
            model_name='ctrlbom',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kurs.ElementsBase'),
        ),
    ]
